---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 3 # Increase this timeout value as needed
    steps:
      # Test local action
      - name: "Run action: ${{ github.repository }}"
        id: test-local
        uses: $/

      # Test local action
      - name: "Run action: ${{ github.repository }} [test-tags-semver]"
        id: semver
        uses: $/
        with:
          repository: 'lfreleng-actions/test-tags-semantic'
          path: 'test-tags-semantic'

      # Test local action
      - name: "Run action: ${{ github.repository }} [test-tags-calver]"
        id: calver
        uses: $/
        with:
          repository: 'lfreleng-actions/test-tags-calver'
          path: 'test-tags-calver'

      - name: "Validate action: ${{ github.repository }}"
        shell: bash
        run: |
          # Validate Action Output
          if [ "${STEPS_SEMVER_OUTPUTS_TAG}" \
            != 'v0.1.1' ]; then
            echo 'Error: did not get expected semantic tag result ❌'
            echo "Returned: ${STEPS_SEMVER_OUTPUTS_TAG}"
            echo 'Expected: v0.1.1'
            errors='true'
          elif [ "${STEPS_SEMVER_OUTPUTS_TAG_COUNT}" \
            != '2' ]; then
            echo 'Error: did not get expected semver count ❌'
            echo "Returned: ${STEPS_SEMVER_OUTPUTS_TAG_COUNT}"
            echo 'Expected: 2'
            errors='true'
          elif [ "${STEPS_CALVER_OUTPUTS_TAG}" \
            != '2025.02.01' ]; then
            echo 'Error: did not get expected calver tag result ❌'
            echo "Returned: ${STEPS_CALVER_OUTPUTS_TAG}"
            echo 'Expected: 2025.02.01'
            errors='true'
          elif [ "${STEPS_CALVER_OUTPUTS_TAG_COUNT}" \
            != '2' ]; then
            echo 'Error: did not get expected calver count ❌'
            echo "Returned: ${STEPS_CALVER_OUTPUTS_TAG_COUNT}"
            echo 'Expected: 2'
            errors='true'
          fi

          if [ "$errors" == 'true' ]; then
            echo 'Action validation failed ❌'
            exit 1
          else
            echo 'Action validation passed ✅'
          fi
        env:
          STEPS_SEMVER_OUTPUTS_TAG: ${{ steps.semver.outputs.tag }}
          STEPS_SEMVER_OUTPUTS_TAG_COUNT: ${{ steps.semver.outputs.tag_count }}
          STEPS_CALVER_OUTPUTS_TAG: ${{ steps.calver.outputs.tag }}
          STEPS_CALVER_OUTPUTS_TAG_COUNT: ${{ steps.calver.outputs.tag_count }}
